import type { IngredientDraft, IngredientInputUnit, IngredientSource, NormalizedIngredient } from '../types/domain.ts'

export const ingredientInputUnits: readonly IngredientInputUnit[] = [
  'piece', 'can', 'pack', 'bottle', 'bundle', 'clove', 'cup', 'gram', 'kilogram', 'block',
]

export const ingredientInputUnitLabels: Record<IngredientInputUnit, string> = {
  piece: 'piece',
  can: 'can',
  pack: 'pack',
  bottle: 'bottle',
  bundle: 'bundle',
  clove: 'clove',
  cup: 'cup',
  gram: 'gram',
  kilogram: 'kilogram',
  block: 'block',
}

const aliases: Record<string, string> = {
  itlog: 'egg',
  itlogg: 'egg',
  eggs: 'egg',
  egg: 'egg',
  kamatis: 'tomato',
  kamatises: 'tomato',
  tomatoes: 'tomato',
  tomato: 'tomato',
  sardinas: 'sardines',
  sardine: 'sardines',
  sardines: 'sardines',
  'canned sardine': 'sardines',
  'canned sardines': 'sardines',
  pechay: 'bok choy',
  'bok choy': 'bok choy',
  bawang: 'garlic',
  garlic: 'garlic',
  sibuyas: 'onion',
  onions: 'onion',
  onion: 'onion',
  talong: 'eggplant',
  eggplant: 'eggplant',
  eggplants: 'eggplant',
  tofu: 'tofu',
  tokwa: 'tofu',
  manok: 'chicken',
  chicken: 'chicken',
  baboy: 'pork',
  pork: 'pork',
  hipon: 'shrimp',
  shrimp: 'shrimp',
  isda: 'fish',
  fish: 'fish',
  bangus: 'milkfish',
  milkfish: 'milkfish',
  sitaw: 'long beans',
  'long bean': 'long beans',
  'long beans': 'long beans',
  kalabasa: 'squash',
  squash: 'squash',
  ampalaya: 'bitter melon',
  'bitter melon': 'bitter melon',
  gata: 'coconut milk',
  'coconut milk': 'coconut milk',
  luya: 'ginger',
  ginger: 'ginger',
  suka: 'vinegar',
  vinegar: 'vinegar',
  toyo: 'soy sauce',
  'soy sauce': 'soy sauce',
  'peanut butter': 'peanut butter',
  peanut: 'peanut',
  mani: 'peanut',
  'cooked rice': 'cooked rice',
  kanin: 'cooked rice',
  'leftover rice': 'cooked rice',
  bigas: 'uncooked rice',
  rice: 'uncooked rice',
  'bell pepper': 'bell pepper',
  'bell peppers': 'bell pepper',
  'red pepper': 'bell pepper',
  'green pepper': 'bell pepper',
  repolyo: 'cabbage',
  cabbage: 'cabbage',
  cabbages: 'cabbage',
  karot: 'carrot',
  carrot: 'carrot',
  carrots: 'carrot',
  patatas: 'potato',
  potato: 'potato',
  potatoes: 'potato',
  mais: 'corn',
  corn: 'corn',
  greenbeans: 'green beans',
  'green beans': 'green beans',
  'baguio beans': 'green beans',
  baguio: 'green beans',
  kangkong: 'water spinach',
  'water spinach': 'water spinach',
  'chili leaves': 'chili leaves',
  'dahon ng sili': 'chili leaves',
  gabi: 'taro leaves',
  'taro leaves': 'taro leaves',
  monggo: 'mung beans',
  'mung bean': 'mung beans',
  'mung beans': 'mung beans',
  togue: 'bean sprouts',
  'bean sprout': 'bean sprouts',
  'bean sprouts': 'bean sprouts',
  okra: 'okra',
  sayote: 'chayote',
  chayote: 'chayote',
  papaya: 'green papaya',
  'green papaya': 'green papaya',
  'hilaw na papaya': 'green papaya',
  sampalok: 'tamarind',
  tamarind: 'tamarind',
  'sinigang mix': 'tamarind',
  sampaloc: 'tamarind',
  sili: 'chili',
  chili: 'chili',
  chilies: 'chili',
  'green chili': 'green chili',
  'siling haba': 'green chili',
  'tomato sauce': 'tomato sauce',
  'sarsa ng kamatis': 'tomato sauce',
  atsuete: 'annatto',
  achuete: 'annatto',
  annatto: 'annatto',
  tanglad: 'lemongrass',
  lemongrass: 'lemongrass',
  pandan: 'pandan',
  malunggay: 'malunggay',
  basil: 'basil',
  parsley: 'parsley',
  dahon: 'green onion',
  'green onion': 'green onion',
  'spring onion': 'spring onion',
  'sibuyas dahon': 'green onion',
  harina: 'flour',
  flour: 'flour',
  'rice flour': 'rice flour',
  'harina ng bigas': 'rice flour',
  malagkit: 'glutinous rice',
  'glutinous rice': 'glutinous rice',
  noodles: 'flour noodles',
  canton: 'flour noodles',
  'pancit canton': 'flour noodles',
  'canton noodles': 'flour noodles',
  'pancit canton noodles': 'flour noodles',
  'flour noodles': 'flour noodles',
  'pancit bato': 'pancit bato noodles',
  'pancit bato noodles': 'pancit bato noodles',
  bihon: 'rice noodles',
  'pancit bihon': 'rice noodles',
  'rice noodles': 'rice noodles',
  miki: 'egg noodles',
  'egg noodles': 'egg noodles',
  'pancit miki': 'egg noodles',
  spaghetti: 'spaghetti',
  'garlic rice': 'cooked rice',
  baka: 'beef',
  beef: 'beef',
  'pork belly': 'pork belly',
  liempo: 'pork belly',
  'pork shoulder': 'pork shoulder',
  'pork leg': 'pork leg',
  pata: 'pork leg',
  'pork rind': 'pork rind',
  chicharon: 'pork rind',
  'pork face': 'pork face',
  maskara: 'pork face',
  atay: 'pork liver',
  'pork liver': 'pork liver',
  dugo: 'pork blood',
  'pork blood': 'pork blood',
  giniling: 'ground pork',
  'ground pork': 'ground pork',
  'ground beef': 'ground beef',
  hotdog: 'hotdog',
  longganisa: 'longganisa',
  tapa: 'beef tapa',
  'beef tapa': 'beef tapa',
  tocino: 'pork tocino',
  'pork tocino': 'pork tocino',
  lechon: 'lechon',
  'roast pork': 'roast pork',
  pusit: 'squid',
  squid: 'squid',
  tilapia: 'tilapia',
  crab: 'crab',
  alimango: 'crab',
  tuyo: 'dried fish',
  'dried fish': 'dried fish',
  'smoked fish': 'smoked fish',
  'fish balls': 'fish balls',
  fishball: 'fish balls',
  'fish ball': 'fish balls',
  'squid balls': 'squid balls',
  bagoong: 'shrimp paste',
  'bagoong alamang': 'shrimp paste',
  'shrimp paste': 'shrimp paste',
  patis: 'fish sauce',
  'fish sauce': 'fish sauce',
  asin: 'salt',
  salt: 'salt',
  paminta: 'black pepper',
  pepper: 'black pepper',
  'black pepper': 'black pepper',
  asukal: 'sugar',
  sugar: 'sugar',
  'brown sugar': 'brown sugar',
  mascobado: 'brown sugar',
  mantika: 'oil',
  oil: 'oil',
  butter: 'butter',
  gatas: 'milk',
  milk: 'milk',
  'evaporated milk': 'evaporated milk',
  'condensed milk': 'condensed milk',
  'coconut cream': 'coconut cream',
  'green mango': 'green mango',
  'manggang hilaw': 'green mango',
  saging: 'banana',
  banana: 'banana',
  'saba banana': 'saba banana',
  saba: 'saba banana',
  kamote: 'sweet potato',
  'sweet potato': 'sweet potato',
  cocoa: 'cocoa',
  tableya: 'cocoa',
  'cocoa powder': 'cocoa',
  'egg yolk': 'egg yolk',
  'pula ng itlog': 'egg yolk',
  coconut: 'coconut',
  'shaved ice': 'shaved ice',
  ube: 'ube',
  langka: 'jackfruit',
  jackfruit: 'jackfruit',
  'nata de coco': 'nata de coco',
  raisins: 'raisins',
  pasas: 'raisins',
  mushroom: 'mushroom',
  mushrooms: 'mushroom',
  kabute: 'mushroom',
  cheese: 'cheese',
  keso: 'cheese',
  mayonnaise: 'mayonnaise',
  mayo: 'mayonnaise',
  cornstarch: 'cornstarch',
  'corn starch': 'cornstarch',
  tubig: 'water',
  water: 'water',
  calamansi: 'calamansi',
  lemon: 'lemon',
  'coconut water': 'coconut water',
  'tubig ng niyog': 'coconut water',
  'young coconut': 'young coconut',
  'buko': 'young coconut',
  'tamarind leaves': 'tamarind leaves',
  'dahon ng sampalok': 'tamarind leaves',
  'banana blossom': 'banana blossom',
  'puso ng saging': 'banana blossom',
  pineapple: 'pineapple',
  pinya: 'pineapple',
  goat: 'goat',
  kambing: 'goat',
  miso: 'miso',
  mussels: 'mussels',
  tahong: 'mussels',
  'thick rice noodles': 'thick rice noodles',
  'lapad na bihon': 'thick rice noodles',
  'glass noodles': 'glass noodles',
  sotanghon: 'glass noodles',
  'misua noodles': 'misua noodles',
  misua: 'misua noodles',
  'luncheon meat': 'luncheon meat',
  spam: 'luncheon meat',
  'curry powder': 'curry powder',
  kari: 'curry powder',
  'star anise': 'star anise',
  anis: 'star anise',
  'bottle gourd': 'bottle gourd',
  upo: 'bottle gourd',
  'sponge gourd': 'sponge gourd',
  patola: 'sponge gourd',
  'young jackfruit': 'young jackfruit',
  'langka hilaw': 'young jackfruit',
  'pork cracklings': 'pork cracklings',
  chorizo: 'chorizo',
  gravy: 'gravy',
  ketchup: 'ketchup',
  'banana ketchup': 'banana ketchup',
  cucumber: 'cucumber',
  pipino: 'cucumber',
  'oyster sauce': 'oyster sauce',
  'bread crumbs': 'bread crumbs',
  breadcrumbs: 'bread crumbs',
  'water chestnut': 'water chestnut',
  'lye water': 'lye water',
  'quail egg': 'quail egg',
  'itlog ng pugo': 'quail egg',
  'coconut vinegar': 'coconut vinegar',
  'beef tripe': 'beef tripe',
  'corned beef': 'corned beef',
  'corned-beef': 'corned beef',
  cornedbeef: 'corned beef',
  'karne norte': 'corned beef',
  'canned corned beef': 'corned beef',
  'bay leaf': 'bay leaf',
  'bay leaves': 'bay leaf',
  laurel: 'bay leaf',
  'dahon ng laurel': 'bay leaf',
  radish: 'radish',
  labanos: 'radish',
  radishes: 'radish',
  'beef shank': 'beef shank',
  bulalo: 'beef shank',
  'beef marrow bone': 'beef marrow bone',
  'buto buto': 'beef marrow bone',
  'beef short rib': 'beef short rib',
  'short ribs': 'beef short rib',
  oxtail: 'oxtail',
  'buntot ng baka': 'oxtail',
  'beef stew meat': 'beef stew meat',
  'liver spread': 'liver spread',
  reno: 'liver spread',
  'chicken liver': 'chicken liver',
  'atay ng manok': 'chicken liver',
  intestine: 'intestine',
  isaw: 'intestine',
  peas: 'peas',
  'green peas': 'peas',
  gisantes: 'peas',
  'black beans': 'black beans',
  tausi: 'black beans',
  'red beans': 'red beans',
  zucchini: 'zucchini',
  lettuce: 'lettuce',
  spinach: 'spinach',
  'string beans': 'green beans',
  'lumpia wrapper': 'lumpia wrapper',
  'lumpia wrappers': 'lumpia wrapper',
  'balat ng lumpia': 'lumpia wrapper',
  'spring roll wrapper': 'spring roll wrapper',
  'spring roll wrappers': 'spring roll wrapper',
  'ground chicken': 'ground chicken',
  'giniling na manok': 'ground chicken',
  'salted fish': 'salted fish',
  daing: 'salted fish',
  tuna: 'tuna',
  'canned tuna': 'tuna',
  'leftover chicken': 'chicken',
  safflower: 'safflower',
  kasubha: 'safflower',
  pickle: 'pickle',
  pickles: 'pickle',
  atsara: 'pickle',
  'salted egg': 'salted egg',
  'itlog na maalat': 'salted egg',
  'itlog maalat': 'salted egg',
  'pie crust': 'pie crust',
  sinangag: 'cooked rice',
  'fried rice': 'cooked rice',
}

const displayNames: Record<string, string> = {
  egg: 'itlog',
  tomato: 'kamatis',
  sardines: 'sardinas',
  'bok choy': 'pechay',
  garlic: 'bawang',
  onion: 'sibuyas',
  eggplant: 'talong',
  tofu: 'tofu',
  chicken: 'manok',
  pork: 'baboy',
  'cooked rice': 'kanin',
  'uncooked rice': 'bigas',
  'bell pepper': 'bell pepper',
  shrimp: 'hipon',
  fish: 'isda',
  milkfish: 'bangus',
  'long beans': 'sitaw',
  squash: 'kalabasa',
  'bitter melon': 'ampalaya',
  'coconut milk': 'gata',
  ginger: 'luya',
  vinegar: 'suka',
  'soy sauce': 'toyo',
  'peanut butter': 'peanut butter',
  peanut: 'mani',
  'corned beef': 'corned beef',
  'bay leaf': 'laurel',
  radish: 'labanos',
  'beef shank': 'bulalo',
  'liver spread': 'liver spread',
  peas: 'gisantes',
  'chicken liver': 'atay ng manok',
  'black beans': 'tausi',
  'lumpia wrapper': 'balat ng lumpia',
  'salted egg': 'itlog na maalat',
  'salted fish': 'daing',
  safflower: 'kasubha',
}

const unitAliases: Array<[IngredientInputUnit, string[]]> = [
  ['kilogram', ['kilograms', 'kilogram', 'kilos', 'kilo', 'kg']],
  ['bundle', ['bundles', 'bundle', 'tali']],
  ['bottle', ['bottles', 'bottle', 'bote']],
  ['clove', ['cloves', 'clove', 'butil']],
  ['piece', ['pieces', 'piece', 'pcs', 'pc', 'piraso']],
  ['can', ['cans', 'can', 'lata', 'latas']],
  ['pack', ['packs', 'pack', 'pak']],
  ['gram', ['grams', 'gram', 'gramo', 'gramos', 'g']],
  ['cup', ['cups', 'cup', 'tasa']],
  ['block', ['blocks', 'block']],
]

function normalizeKey(value: string) {
  return value.trim().toLowerCase().replace(/[-_]/g, ' ').replace(/\s+/g, ' ')
}

export function normalizeIngredientName(value: string) {
  const normalized = normalizeKey(value).replace(/^[,.;:]+|[,.;:]+$/g, '')
  return aliases[normalized] ?? normalized
}

function slugify(value: string) {
  return normalizeKey(value).replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'ingredient'
}

function splitInput(input: string) {
  return input
    .replace(/\b(?:may|ako|meron)\b/gi, '')
    .split(/\r?\n|,|\band\b|\bat\b/gi)
    .map((item) => item.trim())
    .filter(Boolean)
}

function parseUnit(value: string): { unit: IngredientInputUnit; name: string } {
  const norm = normalizeKey(value)
  if (aliases[norm]) {
    return { unit: 'piece', name: value.replace(/^(?:of|ng|na)\s+/i, '') }
  }

  for (const [unit, aliasesForUnit] of unitAliases) {
    const alias = aliasesForUnit.find((candidate) => new RegExp(`^${candidate.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?:\\s|$)`, 'i').test(value))
    if (alias) {
      return { unit, name: value.slice(alias.length).trim().replace(/^(?:of|ng|na)\s+/i, '') }
    }
  }
  return { unit: 'piece', name: value.replace(/^(?:of|ng|na)\s+/i, '') }
}

function normalizeItem(originalText: string, index: number, source: IngredientSource): NormalizedIngredient {
  const cleanedText = originalText.trim().replace(/\s+/g, ' ')
  const quantityMatch = cleanedText.match(/^(\d+(?:[.,]\d+)?)\s*/)
  const quantity = quantityMatch ? Number(quantityMatch[1].replace(',', '.')) : 1
  const withoutQuantity = (quantityMatch ? cleanedText.slice(quantityMatch[0].length) : cleanedText).replace(/^(?:of|ng|na)\s+/i, '')
  const { unit, name: parsedName } = parseUnit(withoutQuantity)
  const normalizedName = normalizeKey(parsedName)
  const canonicalName = normalizeIngredientName(normalizedName)
  const isKnown = canonicalName !== normalizedName || Boolean(aliases[normalizedName])
  const displayName = displayNames[canonicalName] ?? parsedName.trim()

  return {
    id: `${source}-${slugify(canonicalName)}-${index}`,
    name: displayName,
    canonicalName,
    originalText: cleanedText,
    quantity: Number.isFinite(quantity) && quantity > 0 ? quantity : 1,
    unit,
    source,
    confidence: isKnown ? 'high' : 'low',
    available: true,
  }
}

export function normalizeIngredientInput(input: string, source: IngredientSource = 'manual') {
  return splitInput(input).map((item, index) => normalizeItem(item, index, source))
}

export function normalizeIngredientDraft(input: IngredientDraft, source: IngredientSource = 'manual'): NormalizedIngredient | undefined {
  const parsed = normalizeIngredientInput(`1 piece ${input.name}`, source)[0]
  if (!parsed || !input.name.trim()) return undefined
  return {
    ...parsed,
    originalText: input.name.trim(),
    quantity: 1,
    unit: 'piece',
  }
}

export function formatIngredientQuantity(item: Pick<NormalizedIngredient, 'quantity' | 'unit'>) {
  return `${item.quantity} ${ingredientInputUnitLabels[item.unit]}`
}

export function formatIngredientInput(items: NormalizedIngredient[]) {
  return items.map((item) => item.quantity === 1 && item.unit === 'piece' ? item.name : `${item.quantity} ${item.unit} ${item.name}`).join(', ')
}

export function isIngredientInputUnit(value: string | null | undefined): value is IngredientInputUnit {
  return Boolean(value && ingredientInputUnits.includes(value as IngredientInputUnit))
}
