import type { IngredientDraft, IngredientInputUnit, IngredientSource, NormalizedIngredient } from '../types/domain.ts'

export const ingredientInputUnits: readonly IngredientInputUnit[] = [
  'piece', 'can', 'pack', 'bottle', 'bundle', 'clove', 'cup', 'gram', 'kilogram', 'block',
]

export const ingredientInputUnitLabels: Record<IngredientInputUnit, string> = {
  piece: 'piece',
  can: 'can',
  pack: 'pack',
  bottle: 'bottle',
  bundle: 'bundle',
  clove: 'clove',
  cup: 'cup',
  gram: 'gram',
  kilogram: 'kilogram',
  block: 'block',
}

const aliases: Record<string, string> = {

  itlog: 'egg',
  itlogg: 'egg',
  eggs: 'egg',
  egg: 'egg',
  'egg yolk': 'egg yolk',
  'pula ng itlog': 'egg yolk',
  'quail egg': 'quail egg',
  'quail eggs': 'quail egg',
  'itlog ng pugo': 'quail egg',
  'salted egg': 'salted egg',
  'salted eggs': 'salted egg',
  'itlog na maalat': 'salted egg',
  'itlog maalat': 'salted egg',

  kamatis: 'tomato',
  kamatises: 'tomato',
  tomatoes: 'tomato',
  tomato: 'tomato',
  pechay: 'bok choy',
  'bok choy': 'bok choy',
  'bokchoy': 'bok choy',
  'pak choi': 'bok choy',
  talong: 'eggplant',
  eggplant: 'eggplant',
  eggplants: 'eggplant',
  'aubergine': 'eggplant',
  sibuyas: 'onion',
  onions: 'onion',
  onion: 'onion',
  'red onion': 'onion',
  'white onion': 'onion',
  'sibuyas bombay': 'onion',
  repolyo: 'cabbage',
  cabbage: 'cabbage',
  cabbages: 'cabbage',
  karot: 'carrot',
  carrot: 'carrot',
  carrots: 'carrot',
  patatas: 'potato',
  potato: 'potato',
  potatoes: 'potato',
  mais: 'corn',
  corn: 'corn',
  'sweet corn': 'corn',
  'corn on the cob': 'corn',
  kangkong: 'water spinach',
  'water spinach': 'water spinach',
  'morning glory': 'water spinach',
  sitaw: 'long beans',
  'long bean': 'long beans',
  'long beans': 'long beans',
  'yard long beans': 'long beans',
  'snake beans': 'long beans',
  kalabasa: 'squash',
  squash: 'squash',
  'butternut squash': 'squash',
  'pumpkin': 'squash',
  ampalaya: 'bitter melon',
  'bitter melon': 'bitter melon',
  'bitter gourd': 'bitter melon',
  'ampalya': 'bitter melon',
  okra: 'okra',
  'lady finger': 'okra',
  'ladyfinger': 'okra',
  sayote: 'chayote',
  chayote: 'chayote',
  'chayotes': 'chayote',
  'mirliton': 'chayote',
  papaya: 'green papaya',
  'green papaya': 'green papaya',
  'hilaw na papaya': 'green papaya',
  'unripe papaya': 'green papaya',
  greenbeans: 'green beans',
  'green beans': 'green beans',
  'baguio beans': 'green beans',
  baguio: 'green beans',
  'string beans': 'green beans',
  'snap beans': 'green beans',
  'french beans': 'green beans',
  'habichuelas': 'green beans',
  'bell pepper': 'bell pepper',
  'bell peppers': 'bell pepper',
  'red pepper': 'bell pepper',
  'green pepper': 'bell pepper',
  'red bell pepper': 'bell pepper',
  'green bell pepper': 'bell pepper',
  'yellow bell pepper': 'bell pepper',
  'capsicum': 'bell pepper',
  radish: 'radish',
  labanos: 'radish',
  radishes: 'radish',
  'white radish': 'radish',
  zucchini: 'zucchini',
  'zucchinis': 'zucchini',
  'courgette': 'zucchini',
  lettuce: 'lettuce',
  spinach: 'spinach',
  'espinaka': 'spinach',
  cucumber: 'cucumber',
  pipino: 'cucumber',
  cucumbers: 'cucumber',

  'chili leaves': 'chili leaves',
  'dahon ng sili': 'chili leaves',
  gabi: 'taro leaves',
  'taro leaves': 'taro leaves',
  'dahon ng gabi': 'taro leaves',
  'taro leaf': 'taro leaves',
  malunggay: 'malunggay',
  moringa: 'malunggay',
  'dahon ng malunggay': 'malunggay',
  basil: 'basil',
  'sweet basil': 'basil',
  parsley: 'parsley',
  'kinchay': 'parsley',
  'wansoy': 'cilantro',
  cilantro: 'cilantro',
  coriander: 'cilantro',
  'coriander leaves': 'cilantro',
  dahon: 'green onion',
  'green onion': 'green onion',
  'green onions': 'green onion',
  'sibuyas dahon': 'green onion',
  'spring onion': 'spring onion',
  'spring onions': 'spring onion',
  leeks: 'spring onion',

  monggo: 'mung beans',
  'mung bean': 'mung beans',
  'mung beans': 'mung beans',
  'mongo': 'mung beans',
  'munggo': 'mung beans',
  'green beans mung': 'mung beans',
  togue: 'bean sprouts',
  'bean sprout': 'bean sprouts',
  'bean sprouts': 'bean sprouts',
  'toge': 'bean sprouts',
  peas: 'peas',
  'green peas': 'peas',
  gisantes: 'peas',
  'sweet peas': 'peas',
  'chick peas': 'chickpeas',
  chickpeas: 'chickpeas',
  'garbanzo': 'chickpeas',
  'black beans': 'black beans',
  tausi: 'black beans',
  'fermented black beans': 'black beans',
  'red beans': 'red beans',
  'kidney beans': 'red beans',
  'red kidney beans': 'red beans',

  'bottle gourd': 'bottle gourd',
  upo: 'bottle gourd',
  'sponge gourd': 'sponge gourd',
  patola: 'sponge gourd',
  'luffa': 'sponge gourd',
  'young jackfruit': 'young jackfruit',
  'langka hilaw': 'young jackfruit',
  'unripe jackfruit': 'young jackfruit',
  'green jackfruit': 'young jackfruit',
  'banana blossom': 'banana blossom',
  'puso ng saging': 'banana blossom',
  'banana flower': 'banana blossom',
  'banana heart': 'banana blossom',

  bawang: 'garlic',
  garlic: 'garlic',
  'garlic cloves': 'garlic',
  luya: 'ginger',
  ginger: 'ginger',
  'fresh ginger': 'ginger',
  sili: 'chili',
  chili: 'chili',
  chilies: 'chili',
  'chilli': 'chili',
  'chillies': 'chili',
  'hot pepper': 'chili',
  'siling labuyo': 'chili',
  'green chili': 'green chili',
  'siling haba': 'green chili',
  'finger chili': 'green chili',
  'long chili': 'green chili',
  atsuete: 'annatto',
  achuete: 'annatto',
  annatto: 'annatto',
  'annatto seeds': 'annatto',
  'annatto powder': 'annatto',
  tanglad: 'lemongrass',
  lemongrass: 'lemongrass',
  'lemon grass': 'lemongrass',
  pandan: 'pandan',
  'pandan leaves': 'pandan',
  'dahon ng pandan': 'pandan',
  'bay leaf': 'bay leaf',
  'bay leaves': 'bay leaf',
  laurel: 'bay leaf',
  'dahon ng laurel': 'bay leaf',
  'laurel leaf': 'bay leaf',
  'star anise': 'star anise',
  anis: 'star anise',
  'anise': 'star anise',
  safflower: 'safflower',
  kasubha: 'safflower',

  suka: 'vinegar',
  vinegar: 'vinegar',
  'white vinegar': 'vinegar',
  'cane vinegar': 'vinegar',
  'coconut vinegar': 'coconut vinegar',
  'sukang tuba': 'coconut vinegar',
  'sukang niyog': 'coconut vinegar',
  toyo: 'soy sauce',
  'soy sauce': 'soy sauce',
  'soysauce': 'soy sauce',
  'soy': 'soy sauce',
  patis: 'fish sauce',
  'fish sauce': 'fish sauce',
  bagoong: 'shrimp paste',
  'bagoong alamang': 'shrimp paste',
  'shrimp paste': 'shrimp paste',
  alamang: 'shrimp paste',
  'bagoong isda': 'fish paste',
  'fish paste': 'fish paste',
  'tomato sauce': 'tomato sauce',
  'sarsa ng kamatis': 'tomato sauce',
  'tomato paste': 'tomato sauce',
  'tomato ketchup': 'ketchup',
  ketchup: 'ketchup',
  'banana ketchup': 'banana ketchup',
  'jufran': 'banana ketchup',
  'oyster sauce': 'oyster sauce',
  'hoisin sauce': 'hoisin sauce',
  'sesame oil': 'sesame oil',
  'curry powder': 'curry powder',
  kari: 'curry powder',
  'curry': 'curry powder',
  miso: 'miso',
  'miso paste': 'miso',

  asin: 'salt',
  salt: 'salt',
  'sea salt': 'salt',
  'iodized salt': 'salt',
  'rock salt': 'salt',
  paminta: 'black pepper',
  pepper: 'black pepper',
  'black pepper': 'black pepper',
  'ground pepper': 'black pepper',
  'cracked pepper': 'black pepper',
  'white pepper': 'white pepper',
  asukal: 'sugar',
  sugar: 'sugar',
  'white sugar': 'sugar',
  'brown sugar': 'brown sugar',
  mascobado: 'brown sugar',
  'muscovado': 'brown sugar',
  'raw sugar': 'brown sugar',
  'coconut sugar': 'brown sugar',
  mantika: 'oil',
  oil: 'oil',
  'cooking oil': 'oil',
  'vegetable oil': 'oil',
  'canola oil': 'oil',
  'palm oil': 'oil',
  'olive oil': 'olive oil',
  butter: 'butter',
  'unsalted butter': 'butter',
  'salted butter': 'butter',
  'margarine': 'butter',

  gatas: 'milk',
  milk: 'milk',
  'fresh milk': 'milk',
  'whole milk': 'milk',
  'evaporated milk': 'evaporated milk',
  'evap milk': 'evaporated milk',
  'condensed milk': 'condensed milk',
  'sweetened condensed milk': 'condensed milk',
  cream: 'cream',
  'heavy cream': 'cream',
  'all purpose cream': 'cream',
  'cooking cream': 'cream',
  cheese: 'cheese',
  keso: 'cheese',
  'cheddar': 'cheese',
  'cheddar cheese': 'cheese',
  'quick melt cheese': 'cheese',
  'eden cheese': 'cheese',
  'cream cheese': 'cream cheese',
  'kesong puti': 'cream cheese',
  mayonnaise: 'mayonnaise',
  mayo: 'mayonnaise',

  gata: 'coconut milk',
  'coconut milk': 'coconut milk',
  'kakang gata': 'coconut milk',
  'canned coconut milk': 'coconut milk',
  'coconut cream': 'coconut cream',
  coconut: 'coconut',
  niyog: 'coconut',
  'desiccated coconut': 'coconut',
  'grated coconut': 'coconut',
  'coconut water': 'coconut water',
  'tubig ng niyog': 'coconut water',
  'buko juice': 'coconut water',
  'young coconut': 'young coconut',
  'buko': 'young coconut',

  manok: 'chicken',
  chicken: 'chicken',
  'chicken breast': 'chicken',
  'chicken thigh': 'chicken',
  'chicken leg': 'chicken',
  'chicken wings': 'chicken',
  'chicken drumstick': 'chicken',
  'chicken quarter': 'chicken',
  'leftover chicken': 'chicken',
  'ground chicken': 'ground chicken',
  'giniling na manok': 'ground chicken',
  'minced chicken': 'ground chicken',
  'chicken liver': 'chicken liver',
  'atay ng manok': 'chicken liver',

  baboy: 'pork',
  pork: 'pork',
  'pork chop': 'pork',
  'pork loin': 'pork',
  'pork ribs': 'pork',
  'pork belly': 'pork belly',
  liempo: 'pork belly',
  'liempos': 'pork belly',
  'pork liempo': 'pork belly',
  'pork shoulder': 'pork shoulder',
  'kasim': 'pork shoulder',
  'pork kasim': 'pork shoulder',
  'pork leg': 'pork leg',
  pata: 'pork leg',
  'pork pata': 'pork leg',
  'pork rind': 'pork rind',
  chicharon: 'pork rind',
  'chicharron': 'pork rind',
  'pork rinds': 'pork rind',
  'pork cracklings': 'pork cracklings',
  'crackling': 'pork cracklings',
  'tsitsaron': 'pork cracklings',
  'pork face': 'pork face',
  maskara: 'pork face',
  'pig face': 'pork face',
  atay: 'pork liver',
  'pork liver': 'pork liver',
  'liver': 'pork liver',
  dugo: 'pork blood',
  'pork blood': 'pork blood',
  'pig blood': 'pork blood',
  giniling: 'ground pork',
  'ground pork': 'ground pork',
  'minced pork': 'ground pork',
  'pork giniling': 'ground pork',
  intestine: 'intestine',
  isaw: 'intestine',
  'pork intestine': 'intestine',

  baka: 'beef',
  beef: 'beef',
  'beef steak': 'beef',
  'beef shank': 'beef shank',
  bulalo: 'beef shank',
  'beef shanks': 'beef shank',
  'beef marrow bone': 'beef marrow bone',
  'buto buto': 'beef marrow bone',
  'marrow bone': 'beef marrow bone',
  'bone marrow': 'beef marrow bone',
  'beef short rib': 'beef short rib',
  'short ribs': 'beef short rib',
  'beef ribs': 'beef short rib',
  oxtail: 'oxtail',
  'buntot ng baka': 'oxtail',
  'ox tail': 'oxtail',
  'beef stew meat': 'beef stew meat',
  'stewing beef': 'beef stew meat',
  'beef cubes': 'beef stew meat',
  'ground beef': 'ground beef',
  'minced beef': 'ground beef',
  'beef giniling': 'ground beef',
  'beef tripe': 'beef tripe',
  'tripe': 'beef tripe',
  'goto': 'beef tripe',
  'tuwalya ng baka': 'beef tripe',

  goat: 'goat',
  kambing: 'goat',
  'goat meat': 'goat',
  'chevon': 'goat',

  hotdog: 'hotdog',
  'hot dog': 'hotdog',
  'hotdogs': 'hotdog',
  'vienna sausage': 'hotdog',
  longganisa: 'longganisa',
  'longanisa': 'longganisa',
  'longganiza': 'longganisa',
  'filipino sausage': 'longganisa',
  tapa: 'beef tapa',
  'beef tapa': 'beef tapa',
  'cured beef': 'beef tapa',
  tocino: 'pork tocino',
  'pork tocino': 'pork tocino',
  'chicken tocino': 'pork tocino',
  lechon: 'lechon',
  'lechon baboy': 'lechon',
  'roast pork': 'roast pork',
  'roasted pork': 'roast pork',
  chorizo: 'chorizo',
  'longganisang chorizo': 'chorizo',
  'spanish chorizo': 'chorizo',
  'liver spread': 'liver spread',
  reno: 'liver spread',
  'pork liver spread': 'liver spread',
  'corned beef': 'corned beef',
  'corned-beef': 'corned beef',
  cornedbeef: 'corned beef',
  'karne norte': 'corned beef',
  'canned corned beef': 'corned beef',
  'luncheon meat': 'luncheon meat',
  spam: 'luncheon meat',
  'canned meat': 'luncheon meat',
  'lunchon meat': 'luncheon meat',
  gravy: 'gravy',

  hipon: 'shrimp',
  shrimp: 'shrimp',
  shrimps: 'shrimp',
  'prawns': 'shrimp',
  'prawn': 'shrimp',
  'sugpo': 'shrimp',
  isda: 'fish',
  fish: 'fish',
  'fresh fish': 'fish',
  bangus: 'milkfish',
  milkfish: 'milkfish',
  'milk fish': 'milkfish',
  tilapia: 'tilapia',
  'st. peter fish': 'tilapia',
  tuna: 'tuna',
  'canned tuna': 'tuna',
  'tuna flakes': 'tuna',
  'century tuna': 'tuna',
  pusit: 'squid',
  squid: 'squid',
  'squids': 'squid',
  'calamari': 'squid',
  crab: 'crab',
  alimango: 'crab',
  'crabs': 'crab',
  'alimasag': 'crab',
  mussels: 'mussels',
  tahong: 'mussels',
  'mussel': 'mussels',
  'green mussels': 'mussels',
  'clams': 'clams',
  'halaan': 'clams',
  'tulya': 'clams',
  'oyster': 'oyster',
  'oysters': 'oyster',
  'talaba': 'oyster',
  tuyo: 'dried fish',
  'dried fish': 'dried fish',
  'tuyo fish': 'dried fish',
  'smoked fish': 'smoked fish',
  'tinapa': 'smoked fish',
  'salted fish': 'salted fish',
  daing: 'salted fish',
  'dried salted fish': 'salted fish',
  'fish balls': 'fish balls',
  fishball: 'fish balls',
  'fish ball': 'fish balls',
  'squid balls': 'squid balls',
  'squid ball': 'squid balls',

  tofu: 'tofu',
  tokwa: 'tofu',
  'firm tofu': 'tofu',
  'soft tofu': 'tofu',
  'silken tofu': 'tofu',
  'taho': 'tofu',

  noodles: 'flour noodles',
  canton: 'flour noodles',
  'pancit canton': 'flour noodles',
  'canton noodles': 'flour noodles',
  'pancit canton noodles': 'flour noodles',
  'flour noodles': 'flour noodles',
  'lucky me noodles': 'flour noodles',
  'instant noodles': 'flour noodles',
  'pancit bato': 'pancit bato noodles',
  'pancit bato noodles': 'pancit bato noodles',
  bihon: 'rice noodles',
  'pancit bihon': 'rice noodles',
  'rice noodles': 'rice noodles',
  'rice vermicelli': 'rice noodles',
  'rice sticks': 'rice noodles',
  miki: 'egg noodles',
  'egg noodles': 'egg noodles',
  'pancit miki': 'egg noodles',
  'fresh egg noodles': 'egg noodles',
  'thick rice noodles': 'thick rice noodles',
  'lapad na bihon': 'thick rice noodles',
  'pancit malabon noodles': 'thick rice noodles',
  'palabok noodles': 'thick rice noodles',
  'glass noodles': 'glass noodles',
  sotanghon: 'glass noodles',
  'cellophane noodles': 'glass noodles',
  'sotanghon noodles': 'glass noodles',
  'bean thread noodles': 'glass noodles',
  'misua noodles': 'misua noodles',
  misua: 'misua noodles',
  'wheat vermicelli': 'misua noodles',
  spaghetti: 'spaghetti',
  'spaghetti noodles': 'spaghetti',
  'pasta': 'spaghetti',
  macaroni: 'macaroni',
  'elbow macaroni': 'macaroni',
  'macaroni pasta': 'macaroni',

  'cooked rice': 'cooked rice',
  kanin: 'cooked rice',
  'leftover rice': 'cooked rice',
  'garlic rice': 'cooked rice',
  sinangag: 'cooked rice',
  'fried rice': 'cooked rice',
  'steamed rice': 'cooked rice',
  bigas: 'uncooked rice',
  rice: 'uncooked rice',
  'jasmine rice': 'uncooked rice',
  'white rice': 'uncooked rice',
  malagkit: 'glutinous rice',
  'glutinous rice': 'glutinous rice',
  'sticky rice': 'glutinous rice',
  'sweet rice': 'glutinous rice',
  'malagkit rice': 'glutinous rice',

  harina: 'flour',
  flour: 'flour',
  'all purpose flour': 'flour',
  'ap flour': 'flour',
  'wheat flour': 'flour',
  'rice flour': 'rice flour',
  'harina ng bigas': 'rice flour',
  'galapong': 'rice flour',
  cornstarch: 'cornstarch',
  'corn starch': 'cornstarch',
  'cornflour': 'cornstarch',

  'lumpia wrapper': 'lumpia wrapper',
  'lumpia wrappers': 'lumpia wrapper',
  'balat ng lumpia': 'lumpia wrapper',
  'lumpia skin': 'lumpia wrapper',
  'spring roll wrapper': 'spring roll wrapper',
  'spring roll wrappers': 'spring roll wrapper',
  'wonton wrapper': 'wonton wrapper',
  'wonton wrappers': 'wonton wrapper',

  'green mango': 'green mango',
  'manggang hilaw': 'green mango',
  'unripe mango': 'green mango',
  mango: 'mango',
  mangga: 'mango',
  'ripe mango': 'mango',
  saging: 'banana',
  banana: 'banana',
  bananas: 'banana',
  'saba banana': 'saba banana',
  saba: 'saba banana',
  'cooking banana': 'saba banana',
  'plantain': 'saba banana',
  pineapple: 'pineapple',
  pinya: 'pineapple',
  'canned pineapple': 'pineapple',
  'pineapple tidbits': 'pineapple',
  langka: 'jackfruit',
  jackfruit: 'jackfruit',
  'ripe jackfruit': 'jackfruit',
  calamansi: 'calamansi',
  'kalamansi': 'calamansi',
  'calamondin': 'calamansi',
  'philippine lime': 'calamansi',
  lemon: 'lemon',
  lemons: 'lemon',
  'lemon juice': 'lemon',
  lime: 'lime',
  'dayap': 'lime',

  kamote: 'sweet potato',
  'sweet potato': 'sweet potato',
  'camote': 'sweet potato',
  'sweet potatoes': 'sweet potato',
  'taro': 'taro',
  'gabi root': 'taro',

  sardinas: 'sardines',
  sardine: 'sardines',
  sardines: 'sardines',
  'canned sardine': 'sardines',
  'canned sardines': 'sardines',
  'mega sardines': 'sardines',
  'ligo sardines': 'sardines',
  raisins: 'raisins',
  pasas: 'raisins',
  'raisin': 'raisins',
  pickle: 'pickle',
  pickles: 'pickle',
  atsara: 'pickle',
  'pickled papaya': 'pickle',

  'peanut butter': 'peanut butter',
  peanut: 'peanut',
  mani: 'peanut',
  peanuts: 'peanut',
  'roasted peanuts': 'peanut',
  cashew: 'cashew',
  'cashews': 'cashew',
  'kasuy': 'cashew',

  sampalok: 'tamarind',
  tamarind: 'tamarind',
  'sinigang mix': 'tamarind',
  sampaloc: 'tamarind',
  'tamarind paste': 'tamarind',
  'tamarind powder': 'tamarind',
  'sinigang sa sampalok mix': 'tamarind',
  'knorr sinigang': 'tamarind',
  'tamarind leaves': 'tamarind leaves',
  'dahon ng sampalok': 'tamarind leaves',

  cocoa: 'cocoa',
  tableya: 'cocoa',
  'cocoa powder': 'cocoa',
  'tablea': 'cocoa',
  'chocolate tablea': 'cocoa',
  ube: 'ube',
  'ube halaya': 'ube',
  'purple yam': 'ube',
  'nata de coco': 'nata de coco',
  'shaved ice': 'shaved ice',

  mushroom: 'mushroom',
  mushrooms: 'mushroom',
  kabute: 'mushroom',
  'shiitake': 'mushroom',
  'shiitake mushroom': 'mushroom',
  'oyster mushroom': 'mushroom',
  'button mushroom': 'mushroom',
  'enoki': 'mushroom',

  tubig: 'water',
  water: 'water',
  'lye water': 'lye water',
  'lihia': 'lye water',
  'water chestnut': 'water chestnut',
  'water chestnuts': 'water chestnut',
  'apulid': 'water chestnut',

  'bread crumbs': 'bread crumbs',
  breadcrumbs: 'bread crumbs',
  'panko': 'bread crumbs',
  'pie crust': 'pie crust',
  'pastry crust': 'pie crust',
  'puff pastry': 'pie crust',
  'bread': 'bread',
  'pandesal': 'bread',
  'pan de sal': 'bread',
  'sliced bread': 'bread',
  'tasty bread': 'bread',
  'baking powder': 'baking powder',
  'baking soda': 'baking soda',
  'yeast': 'yeast',

  'cooking wine': 'cooking wine',
  'rice wine': 'cooking wine',
  'sake': 'cooking wine',
}

const displayNames: Record<string, string> = {
  egg: 'itlog',
  tomato: 'kamatis',
  sardines: 'sardinas',
  'bok choy': 'pechay',
  garlic: 'bawang',
  onion: 'sibuyas',
  eggplant: 'talong',
  tofu: 'tokwa',
  chicken: 'manok',
  pork: 'baboy',
  'cooked rice': 'kanin',
  'uncooked rice': 'bigas',
  'bell pepper': 'bell pepper',
  shrimp: 'hipon',
  fish: 'isda',
  milkfish: 'bangus',
  'long beans': 'sitaw',
  squash: 'kalabasa',
  'bitter melon': 'ampalaya',
  'coconut milk': 'gata',
  ginger: 'luya',
  vinegar: 'suka',
  'soy sauce': 'toyo',
  'peanut butter': 'peanut butter',
  peanut: 'mani',
  'corned beef': 'corned beef',
  'bay leaf': 'laurel',
  radish: 'labanos',
  'beef shank': 'bulalo',
  'liver spread': 'liver spread',
  peas: 'gisantes',
  'chicken liver': 'atay ng manok',
  'black beans': 'tausi',
  'lumpia wrapper': 'balat ng lumpia',
  'salted egg': 'itlog na maalat',
  'salted fish': 'daing',
  safflower: 'kasubha',
  cabbage: 'repolyo',
  carrot: 'karot',
  potato: 'patatas',
  corn: 'mais',
  'water spinach': 'kangkong',
  chayote: 'sayote',
  'green papaya': 'papaya',
  'mung beans': 'monggo',
  'bean sprouts': 'togue',
  'taro leaves': 'dahon ng gabi',
  'coconut vinegar': 'sukang tuba',
  beef: 'baka',
  goat: 'kambing',
  'pork belly': 'liempo',
  'pork liver': 'atay',
  'pork blood': 'dugo',
  'ground pork': 'giniling',
  crab: 'alimango',
  mussels: 'tahong',
  'shrimp paste': 'bagoong',
  'fish sauce': 'patis',
  salt: 'asin',
  'black pepper': 'paminta',
  sugar: 'asukal',
  oil: 'mantika',
  'green mango': 'manggang hilaw',
  banana: 'saging',
  pineapple: 'pinya',
  'sweet potato': 'kamote',
  'dried fish': 'tuyo',
  'smoked fish': 'tinapa',
  cucumber: 'pipino',
  tamarind: 'sampalok',
  chili: 'sili',
  annatto: 'atsuete',
  lemongrass: 'tanglad',
  'sponge gourd': 'patola',
  'bottle gourd': 'upo',
  jackfruit: 'langka',
  'young jackfruit': 'langka hilaw',
  'banana blossom': 'puso ng saging',
  oxtail: 'buntot ng baka',
  'beef tripe': 'goto',
  squid: 'pusit',
  'quail egg': 'itlog ng pugo',
  coconut: 'niyog',
  'glutinous rice': 'malagkit',
  'glass noodles': 'sotanghon',
  milk: 'gatas',
  cheese: 'keso',
  longganisa: 'longganisa',
  'pork tocino': 'tocino',
  'beef tapa': 'tapa',
  'ground beef': 'giniling na baka',
  raisins: 'pasas',
}

const unitAliases: Array<[IngredientInputUnit, string[]]> = [
  ['kilogram', ['kilograms', 'kilogram', 'kilos', 'kilo', 'kg']],
  ['bundle', ['bundles', 'bundle', 'tali']],
  ['bottle', ['bottles', 'bottle', 'bote']],
  ['clove', ['cloves', 'clove', 'butil']],
  ['piece', ['pieces', 'piece', 'pcs', 'pc', 'piraso']],
  ['can', ['cans', 'can', 'lata', 'latas']],
  ['pack', ['packs', 'pack', 'pak']],
  ['gram', ['grams', 'gram', 'gramo', 'gramos', 'g']],
  ['cup', ['cups', 'cup', 'tasa']],
  ['block', ['blocks', 'block']],
]

function normalizeKey(value: string) {
  return value.trim().toLowerCase().replace(/[-_]/g, ' ').replace(/\s+/g, ' ')
}

export function normalizeIngredientName(value: string) {
  const normalized = normalizeKey(value).replace(/^[,.;:]+|[,.;:]+$/g, '')
  return aliases[normalized] ?? normalized
}

function slugify(value: string) {
  return normalizeKey(value).replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'ingredient'
}

function splitInput(input: string) {
  return input
    .replace(/\b(?:may|ako|meron)\b/gi, '')
    .split(/\r?\n|,|\band\b|\bat\b/gi)
    .map((item) => item.trim())
    .filter(Boolean)
}

function parseUnit(value: string): { unit: IngredientInputUnit; name: string } {
  const norm = normalizeKey(value)
  if (aliases[norm]) {
    return { unit: 'piece', name: value.replace(/^(?:of|ng|na)\s+/i, '') }
  }

  for (const [unit, aliasesForUnit] of unitAliases) {
    const alias = aliasesForUnit.find((candidate) => new RegExp(`^${candidate.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?:\\s|$)`, 'i').test(value))
    if (alias) {
      return { unit, name: value.slice(alias.length).trim().replace(/^(?:of|ng|na)\s+/i, '') }
    }
  }
  return { unit: 'piece', name: value.replace(/^(?:of|ng|na)\s+/i, '') }
}

function normalizeItem(originalText: string, index: number, source: IngredientSource): NormalizedIngredient {
  const cleanedText = originalText.trim().replace(/\s+/g, ' ')
  const quantityMatch = cleanedText.match(/^(\d+(?:[.,]\d+)?)\s*/)
  const quantity = quantityMatch ? Number(quantityMatch[1].replace(',', '.')) : 1
  const withoutQuantity = (quantityMatch ? cleanedText.slice(quantityMatch[0].length) : cleanedText).replace(/^(?:of|ng|na)\s+/i, '')
  const { unit, name: parsedName } = parseUnit(withoutQuantity)
  const normalizedName = normalizeKey(parsedName)
  const canonicalName = normalizeIngredientName(normalizedName)
  const isKnown = canonicalName !== normalizedName || Boolean(aliases[normalizedName])
  const displayName = displayNames[canonicalName] ?? parsedName.trim()

  return {
    id: `${source}-${slugify(canonicalName)}-${index}`,
    name: displayName,
    canonicalName,
    originalText: cleanedText,
    quantity: Number.isFinite(quantity) && quantity > 0 ? quantity : 1,
    unit,
    source,
    confidence: isKnown ? 'high' : 'low',
    available: true,
  }
}

export function normalizeIngredientInput(input: string, source: IngredientSource = 'manual') {
  return splitInput(input).map((item, index) => normalizeItem(item, index, source))
}

export function normalizeIngredientDraft(input: IngredientDraft, source: IngredientSource = 'manual'): NormalizedIngredient | undefined {
  const parsed = normalizeIngredientInput(`1 piece ${input.name}`, source)[0]
  if (!parsed || !input.name.trim()) return undefined
  return {
    ...parsed,
    originalText: input.name.trim(),
    quantity: 1,
    unit: 'piece',
  }
}

export function formatIngredientQuantity(item: Pick<NormalizedIngredient, 'quantity' | 'unit'>) {
  return `${item.quantity} ${ingredientInputUnitLabels[item.unit]}`
}

export function formatIngredientInput(items: NormalizedIngredient[]) {
  return items.map((item) => item.quantity === 1 && item.unit === 'piece' ? item.name : `${item.quantity} ${item.unit} ${item.name}`).join(', ')
}

export function getAutocompleteSuggestions(query: string, limit = 8) {
  const norm = normalizeKey(query)
  if (!norm) return []

  const matches = Object.keys(aliases).filter((alias) => alias.includes(norm))
  matches.sort((a, b) => {
    const aStarts = a.startsWith(norm)
    const bStarts = b.startsWith(norm)
    if (aStarts && !bStarts) return -1
    if (!aStarts && bStarts) return 1
    return a.length - b.length
  })

  const results: { canonical: string; display: string; alias: string }[] = []
  const seenCanonical = new Set<string>()

  for (const alias of matches) {
    const canonical = aliases[alias]
    if (seenCanonical.has(canonical)) continue

    seenCanonical.add(canonical)
    results.push({
      canonical,
      display: displayNames[canonical] ?? canonical,
      alias
    })

    if (results.length >= limit) break
  }

  return results
}

export function isIngredientInputUnit(value: string | null | undefined): value is IngredientInputUnit {
  return Boolean(value && ingredientInputUnits.includes(value as IngredientInputUnit))
}
