import { RecipeCard } from '../components/RecipeCard.tsx'
import { StatePanel } from '../components/StatePanel.tsx'
import type { Recipe } from '../types/domain.ts'

export interface SavedPageProps { isAuthenticated: boolean; status: string; error: string | null; savedIds: string[]; savedRecipes: Recipe[]; cookedRecipes: Recipe[]; onOpen: (id: string) => void; onUnsave: (id: string) => Promise<void>; onStart: () => void; onSignIn: () => void; onRetry: () => void }

export function SavedPage({ isAuthenticated, status, error, savedIds, savedRecipes, cookedRecipes, onOpen, onUnsave, onStart, onSignIn, onRetry }: SavedPageProps) {
  if (!isAuthenticated) return <div className="page-shell"><StatePanel title="Mag-sign in para makita ang mga recipe mo" description="Pribado sa iyong account ang mga naka-save na recipe at kasaysayan ng pagluluto." actionLabel="Mag-sign in" onAction={onSignIn} secondaryLabel="Maghanap ng lulutuin" onSecondary={onStart} /></div>
  if (status === 'error') return <div className="page-shell"><StatePanel tone="error" title="Hindi ma-load ang mga naka-save mong recipe" description={error ?? 'Suriin ang koneksyon sa Supabase at subukan ulit.'} actionLabel="Subukan ulit" onAction={onRetry} secondaryLabel="Maghanap ng lulutuin" onSecondary={onStart} /></div>
  if (status !== 'ready') return <div className="page-shell"><span className="eyebrow">Mga naka-save na recipe</span><h1>Nilo-load ang mga recipe mo…</h1></div>
  return <div className="page-shell"><span className="eyebrow">Mga naka-save na recipe</span><h1>Itago ang mga recipe na nagustuhan mo.</h1><p className="page-intro">Mag-save ng recipe o markahan ito bilang niluto para mas madali ang susunod mong pagkain.</p>{savedRecipes.length === 0 && cookedRecipes.length === 0 ? <StatePanel title="Wala pang naka-save na recipe" description="Mag-save ng recipe para mabalikan mo ito sa susunod." actionLabel="Maghanap ng lulutuin" onAction={onStart} /> : <><section className="saved-section" aria-labelledby="favorites-heading"><div className="section-heading-row"><h2 id="favorites-heading">Mga paborito</h2><span className="count-badge">{savedRecipes.length}</span></div>{savedRecipes.length > 0 ? <div className="results-grid">{savedRecipes.map((recipe) => <RecipeCard key={recipe.id} recipe={recipe} saved onOpen={() => onOpen(recipe.id)} onToggleSave={() => void onUnsave(recipe.id)} />)}</div> : <p className="muted-copy">Wala pang paborito.</p>}</section><section className="saved-section" aria-labelledby="cooked-heading"><div className="section-heading-row"><h2 id="cooked-heading">Mga niluto ko</h2><span className="count-badge">{cookedRecipes.length}</span></div>{cookedRecipes.length > 0 ? <div className="results-grid">{cookedRecipes.map((recipe) => <RecipeCard key={`${recipe.id}-${recipe.title}`} recipe={recipe} saved={savedIds.includes(recipe.id)} onOpen={() => onOpen(recipe.id)} onToggleSave={() => void onUnsave(recipe.id)} />)}</div> : <p className="muted-copy">Wala ka pang naitalang niluto.</p>}</section></>}</div>
}
