import { RecipeCard } from '../components/RecipeCard.tsx'
import { StatePanel } from '../components/StatePanel.tsx'
import type { Recipe } from '../types/domain.ts'

export interface SavedPageProps { isAuthenticated: boolean; status: string; error: string | null; savedIds: string[]; savedRecipes: Recipe[]; cookedRecipes: Recipe[]; onOpen: (id: string) => void; onUnsave: (id: string) => Promise<void>; onStart: () => void; onSignIn: () => void; onRetry: () => void }

export function SavedPage({ isAuthenticated, status, error, savedIds, savedRecipes, cookedRecipes, onOpen, onUnsave, onStart, onSignIn, onRetry }: SavedPageProps) {
  if (!isAuthenticated) return <div className="page-shell"><StatePanel title="Sign in to see your recipes" description="Your saved meals and cooking history are private to your account." actionLabel="Sign in" onAction={onSignIn} secondaryLabel="Find something to cook" onSecondary={onStart} /></div>
  if (status === 'error') return <div className="page-shell"><StatePanel tone="error" title="We couldn’t load your saved recipes" description={error ?? 'Check your Supabase connection and try again.'} actionLabel="Try again" onAction={onRetry} secondaryLabel="Find something to cook" onSecondary={onStart} /></div>
  if (status !== 'ready') return <div className="page-shell"><span className="eyebrow">Saved recipes</span><h1>Loading your kitchen shelf…</h1></div>
  return <div className="page-shell"><span className="eyebrow">Saved recipes</span><h1>Keep the meals that work.</h1><p className="page-intro">Save a recipe or mark it cooked so your next meal starts with less guesswork.</p>{savedRecipes.length === 0 && cookedRecipes.length === 0 ? <StatePanel title="Wala pang saved recipes" description="Mag-save ng recipe para mabalikan mo sa susunod." actionLabel="Find something to cook" onAction={onStart} /> : <><section className="saved-section" aria-labelledby="favorites-heading"><div className="section-heading-row"><h2 id="favorites-heading">Favorites</h2><span className="count-badge">{savedRecipes.length}</span></div>{savedRecipes.length > 0 ? <div className="results-grid">{savedRecipes.map((recipe) => <RecipeCard key={recipe.id} recipe={recipe} saved onOpen={() => onOpen(recipe.id)} onToggleSave={() => void onUnsave(recipe.id)} />)}</div> : <p className="muted-copy">Wala pang favorites.</p>}</section><section className="saved-section" aria-labelledby="cooked-heading"><div className="section-heading-row"><h2 id="cooked-heading">I cooked this</h2><span className="count-badge">{cookedRecipes.length}</span></div>{cookedRecipes.length > 0 ? <div className="results-grid">{cookedRecipes.map((recipe) => <RecipeCard key={`${recipe.id}-${recipe.title}`} recipe={recipe} saved={savedIds.includes(recipe.id)} onOpen={() => onOpen(recipe.id)} onToggleSave={() => void onUnsave(recipe.id)} />)}</div> : <p className="muted-copy">Wala pang cooking history.</p>}</section></>}</div>
}
